stages:
  data_ingestion:
    cmd: python src/mlProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlProject/pipeline/stage_01_data_ingestion.py
      - src/mlProject/components/data_ingestion.py
      - src/mlProject/entity/config_entity.py
      - src/mlProject/utils/common.py
      - src/mlProject/config/configuration.py
    outs:
      - artifacts/data_ingestion/data.zip
      - artifacts/data_ingestion/winequality-red.csv

  data_validation:
    cmd: python src/mlProject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlProject/pipeline/stage_02_data_validation.py
      - src/mlProject/components/data_validation.py
      - src/mlProject/config/configuration.py
      - src/mlProject/entity/config_entity.py
      - src/mlProject/utils/common.py
      - artifacts/data_ingestion/winequality-red.csv
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/mlProject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlProject/components/data_transformation.py
      - src/mlProject/config/configuration.py
      - src/mlProject/entity/config_entity.py
      - src/mlProject/utils/common.py
    outs:
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv



  model_train:
    cmd: python src/mlProject/pipeline/stage_04_model_trainer.py
    deps:
      - src/mlProject/components/model_trainer.py
      - src/mlProject/entity/config_entity.py
      - src/mlProject/utils/common.py
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train.csv
    outs:
      - artifacts/model_trainer/model.pkl

  model_evaluation:
    cmd: python src/mlProject/pipeline/stage_05_model_evaluation.py
    deps:
      - src/mlProject/pipeline/stage_05_model_evaluation.py
      - src/mlProject/components/model_evaluation.py
      - src/mlProject/entity/config_entity.py
      - src/mlProject/utils/common.py
      - src/mlProject/config/configuration.py
    outs:
      - artifacts/model_evaluation/metrics.json


